language: elisp

services:
  - docker

before_install:
  - mkdir ~/.emacs.d/
  - cd ${TRAVIS_BUILD_DIR}
  - ./copy.sh                    # Copy all the repository files to home

script:
  - ls -l ~/.emacs.d
  - docker run -v ~/.emacs.d:/root/.emacs.d -it --rm silex/emacs:26.2 emacs --batch --load /root/.emacs.d/init.el --kill
